In [18]:
# 페이지에 요청하기 위한 용도
import requests as req
# html 데이터를 만들기 위한 용도
from bs4 import BeautifulSoup as bs
import pandas as pd

In [16]:
url = 'https://finance.naver.com/marketindex/exchangeList.naver'
res = req.get(url)
soup = bs(res.text,'lxml')
title = soup.select('td.tit > a')
sale = soup.select('td.sale')

print(len(title))
print(len(sale))

58
58

In [17]:
title_list = []
sale_list = []
for i in range(len(title)):
    title_list.append(title[i].text.strip())
    sale_list.append(sale[i].text.strip())
print(title_list)
print(sale_list)

['미국 USD', '유럽연합 EUR', '일본 JPY (100엔)', '중국 CNY', '홍콩 HKD', '대만 TWD', '영국 GBP', '오만 OMR', '캐나다 CAD', '스위스 CHF', '스웨덴 SEK', '호주 AUD', '뉴질랜드 NZD', '체코 CZK', '칠레 CLP', '튀르키예 TRY', '몽골 MNT', '이스라엘 ILS', '덴마크 DKK', '노르웨이 NOK', '사우디아라비아 SAR', '쿠웨이트 KWD', '바레인 BHD', '아랍에미리트 AED', '요르단 JOD', '이집트 EGP', '태국 THB', '싱가포르 SGD', '말레이시아 MYR', '인도네시아 IDR 100', '카타르 QAR', '카자흐스탄 KZT', '브루나이 BND', '인도 INR', '파키스탄 PKR', '방글라데시 BDT', '필리핀 PHP', '멕시코 MXN', '브라질 BRL', '베트남 VND 100', '남아프리카 공화국 ZAR', '러시아 RUB', '헝가리 HUF', '폴란드 PLN', '스리랑카 LKR', '알제리 DZD', '케냐 KES', '콜롬비아 COP', '탄자니아 TZS', '네팔 NPR', '루마니아 RON', '리비아 LYD', '마카오 MOP', '미얀마 MMK', '에티오피아 ETB', '우즈베키스탄 UZS', '캄보디아 KHR', '피지 FJD']
['1,325.50', '1,427.89', '907.66', '181.75', '169.00', '41.66', '1,667.81', '3,442.86', '975.56', '1,495.46', '120.21', '850.97', '782.91', '59.13', '1.57', '49.98', '0.38', '348.82', '191.57', '123.52', '353.32', '4,295.06', '3,515.73', '360.87', '1,869.53', '42.90', '37.73', '977.26', '285.21', '8.69', '363.65', '2.87', '977.26', '16.03', '4.37', '12.13', '23.43', '78.89', '271.53', '5.52', '70.81', '13.99', '3.73', '319.52', '4.09', '9.69', '9.15', '0.32', '0.53', '10.02', '289.07', '274.95', '163.97', '0.63', '24.00', '0.11', '0.32', '584.48']

In [19]:
dic = {'통화명': title_list, '매매기준율':sale_list}
 pd.DataFrame(dic)

              통화명     매매기준율
0          미국 USD  1,325.50
1        유럽연합 EUR  1,427.89
2   일본 JPY (100엔)    907.66
3          중국 CNY    181.75
4          홍콩 HKD    169.00
5          대만 TWD     41.66
6          영국 GBP  1,667.81
7          오만 OMR  3,442.86
8         캐나다 CAD    975.56
9         스위스 CHF  1,495.46
10        스웨덴 SEK    120.21
11         호주 AUD    850.97
12       뉴질랜드 NZD    782.91
13         체코 CZK     59.13
14         칠레 CLP      1.57
15       튀르키예 TRY     49.98
16         몽골 MNT      0.38
17       이스라엘 ILS    348.82
18        덴마크 DKK    191.57
19       노르웨이 NOK    123.52
20    사우디아라비아 SAR    353.32
21       쿠웨이트 KWD  4,295.06
22        바레인 BHD  3,515.73
23     아랍에미리트 AED    360.87
24        요르단 JOD  1,869.53
25        이집트 EGP     42.90
26         태국 THB     37.73
27       싱가포르 SGD    977.26
28      말레이시아 MYR    285.21
29  인도네시아 IDR 100      8.69
30        카타르 QAR    363.65
31      카자흐스탄 KZT      2.87
32       브루나이 BND    977.26
33         인도 INR     16.03
34       파키스탄 PKR      4.37
35      방글라데시 BDT     12.13
36        필리핀 PHP     23.43
37        멕시코 MXN     78.89
38        브라질 BRL    271.53
39    베트남 VND 100      5.52
40  남아프리카 공화국 ZAR     70.81
41        러시아 RUB     13.99
42        헝가리 HUF      3.73
43        폴란드 PLN    319.52
44       스리랑카 LKR      4.09
45        알제리 DZD      9.69
46         케냐 KES      9.15
47       콜롬비아 COP      0.32
48       탄자니아 TZS      0.53
49         네팔 NPR     10.02
50       루마니아 RON    289.07
51        리비아 LYD    274.95
52        마카오 MOP    163.97
53        미얀마 MMK      0.63
54      에티오피아 ETB     24.00
55     우즈베키스탄 UZS      0.11
56       캄보디아 KHR      0.32
57         피지 FJD    584.48